#!/bin/bash
make
./teste
cd autogenerated/small
for i in ls *.m; do octave $i; done
mv *.png ./imagesFromScripts
cd ..
cd autogenerated/small
for i in ls *.m; do octave $i; done
mv *.png ./imagesFromScripts
